{
  "hash": "4dc42bcad2083fef335c37474cc6e4aa",
  "result": {
    "engine": "jupyter",
    "markdown": "# Fundamentals: Characteristics of Datasets\nBefore diving into the practical challenges of reading structured datasets, we will first look at some key characteristics of datasets to build a basic understanding of terminology and learn how to handle Python’s built-in tools. At the end of this chapter, we introduce *tidy data*—a fundamental concept for organizing datasets.\n\n::: {#imp-Datensatz .callout-important}\n## Dataset\n\nA dataset is a collection of related data. Datasets contain values associated with one or more variables. Every dataset has a technical format, a structure, at least one variable, and at least one value.\n\n:::\n\n## Technical Format\nThe technical format of a dataset determines how data can be read, processed, and stored. Some examples include:\n\n  - Printed material, e.g., phone book: data like names and phone numbers must be read manually, edited irreversibly with a pen\n  \n  - Punch card, e.g., parking ticket: a reader recognizes the holes and grants one free hour; edited irreversibly with a punch tool\n  \n  - Text file, e.g., population by federal states: can be read, processed, and stored with various computer programs such as text editors, spreadsheets, or programming environments\n  \n  - Hierarchical Data Format (HDF5), e.g., spatial lightning density data: requires specialized software or packages\n\n## Structure\nDatasets store data in a defined n-dimensional structure.\n\n::: {.border}\n![n-dimensional datasets](00-bilder/slicing_mf_mp.png){fig-alt=\"Shown from left to right are one-, two-, and three-dimensional block structures representing datasets. These subfigures are reused and described in more detail in later sections.\"}\n\n*slicing* by Marc Fehr is licensed under [CC-BY-4.0](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file) and available on [GitHub](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen). 2024\n:::\n\n### One-Dimensional Datasets\nThe simplest form of dataset assigns values to a single variable. One-dimensional datasets containing values of the same type (e.g., numbers) are called **vectors**. One-dimensional datasets that can contain different data types are called **lists**. One-dimensional datasets have only one axis: the index, which can be used to access elements.\n\n::: {.border}\n\n![one-dimensional datasets](00-bilder/eindimensionaler-datensatz-slicing-mf-mp.png){width=\"50%\" fig-alt=\"A strip divided into five blocks represents a one-dimensional dataset. The blocks are labeled from 0 to 4 along axis 0 from left to right. A blue arrow goes from block zero to block three, which is highlighted in blue.\"}\n\n*slicing* by Marc Fehr is licensed under [CC-BY-4.0](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file) and available on [GitHub](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen). The graphic was cropped to show only the relevant part and the top label removed. 2024\n:::\n\n&nbsp;\n\nExamples of one-dimensional datasets include a shopping list or the raw list of dice roll results. Using the index, you can, for example, output the dice result at index position 2.\n\n::: {#2d711bbc .cell execution_count=1}\n``` {.python .cell-code}\nprint( *( eyes := [6, 2, 1, 2] ) )\n\nprint(f\"The dice result at index position 2 is: {eyes[2]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n6 2 1 2\nThe dice result at index position 2 is: 1\n```\n:::\n:::\n\n\n### Reading One-Dimensional Data with Python\nAt this point, let’s briefly revisit content from the [Python Fundamentals module](https://bausteine-der-datenanalyse.github.io/w-python/output/book/):  \nPython’s base accesses files via *file objects*. You have already learned about these functions and methods in the Python module. Accessing files through Python’s base functionality is a reliable fallback option and also useful for determining a file’s encoding.\n\n::: {#tip-openundco .callout-tip collapse=\"false\"}\n## Quick Review: Core Python Functions and Methods\n\n- The function `os.getcwd()` from the `os` module returns the current working directory. You can change it with `os.cwd(path)`.\n- The function `open(filepath, mode = 'r')` opens a file in read mode and returns a file object.\n- Information about the file object can be retrieved using various attributes: `file_object.name`, `os.path.basename(file_object.name)`, `file_object.closed`, `file_object.mode`, `file_object.encoding`\n- The file object can be read using methods such as `file_object.read()`, `file_object.readline()`, `file_object.readlines()`, or the function `list(file_object)`.\n- The method `file_object.close()` closes the file and releases it for use by other programs.\n\n:::\n\n**Read the file \"python.txt\" located in the path \"skript/01-daten/\".**\n\n - Determine the file’s encoding.\n\n - Remove the first line from the text and output the remaining text using Python.\n\n - How can the text be displayed correctly?\n\n::: {#tip-pythonbasis .callout-tip collapse=\"true\"}\n## Example Solution for python.txt\n\n::: {#691bd115 .cell execution_count=2}\n``` {.python .cell-code}\nfilepath = \"01-daten/\" + \"python.txt\"\nfile_object = open(filepath, mode = 'r')\n\n# Determine the file encoding\nprint(f\"The file encoding is: {file_object.encoding}\")\n\n# Output text\ntext_as_list = list(file_object)\n\nfor i in range(1, len(text_as_list)):\n  print(text_as_list[i])\n\n# Close the file\nfile_object.close()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe file encoding is: UTF-8\n\n\nPython ist eine universell nutzbare, üblicherweise interpretierte, höhere Programmiersprache.[14] Sie hat den Anspruch, einen gut lesbaren, knappen Programmierstil zu fördern.[15] So werden beispielsweise Blöcke nicht durch geschweifte Klammern, sondern durch Einrückungen strukturiert. \n\nPython wurde mit dem Ziel größter Einfachheit und Übersichtlichkeit entworfen. Dies wird vor allem durch zwei Maßnahmen erreicht. Zum einen kommt die Sprache mit relativ wenigen Schlüsselwörtern aus.[49] Zum anderen ist die Syntax reduziert und auf Übersichtlichkeit optimiert. Dadurch lassen sich Python-basierte Skripte deutlich knapper formulieren als in anderen Sprachen.[50]\n\nVan Rossum legte bei der Entwicklung großen Wert auf eine Standardbibliothek, die überschaubar und leicht erweiterbar ist. Dies war Ergebnis seiner schlechten Erfahrung mit der Sprache ABC, in der das Gegenteil der Fall ist.[51] Dieses Konzept ermöglicht, in Python Module aufzurufen, die in anderen Programmiersprachen geschrieben wurden, etwa um Schwächen von Python auszugleichen. Beispielsweise können für zeitkritische Teile in maschinennäheren Sprachen wie C implementierte Routinen aufgerufen werden.\n\n\n\nAuszug aus https://de.wikipedia.org/wiki/Python_(Programmiersprache), abgerufen am 20.02.2025\n```\n:::\n:::\n\n\nSelect UTF-8 encoding.\n\n::: {#38a76d61 .cell execution_count=3}\n``` {.python .cell-code}\n# Choose UTF-8 encoding to support European special characters\nfile_object = open(filepath, mode = 'r', encoding = 'utf-8')\n\n# Output text\ntext_as_list = list(file_object)\n\nfor i in range(1, len(text_as_list)):\n  print(text_as_list[i])\n\n# Close the file\nfile_object.close()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\nPython ist eine universell nutzbare, üblicherweise interpretierte, höhere Programmiersprache.[14] Sie hat den Anspruch, einen gut lesbaren, knappen Programmierstil zu fördern.[15] So werden beispielsweise Blöcke nicht durch geschweifte Klammern, sondern durch Einrückungen strukturiert. \n\nPython wurde mit dem Ziel größter Einfachheit und Übersichtlichkeit entworfen. Dies wird vor allem durch zwei Maßnahmen erreicht. Zum einen kommt die Sprache mit relativ wenigen Schlüsselwörtern aus.[49] Zum anderen ist die Syntax reduziert und auf Übersichtlichkeit optimiert. Dadurch lassen sich Python-basierte Skripte deutlich knapper formulieren als in anderen Sprachen.[50]\n\nVan Rossum legte bei der Entwicklung großen Wert auf eine Standardbibliothek, die überschaubar und leicht erweiterbar ist. Dies war Ergebnis seiner schlechten Erfahrung mit der Sprache ABC, in der das Gegenteil der Fall ist.[51] Dieses Konzept ermöglicht, in Python Module aufzurufen, die in anderen Programmiersprachen geschrieben wurden, etwa um Schwächen von Python auszugleichen. Beispielsweise können für zeitkritische Teile in maschinennäheren Sprachen wie C implementierte Routinen aufgerufen werden.\n\n\n\nAuszug aus https://de.wikipedia.org/wiki/Python_(Programmiersprache), abgerufen am 20.02.2025\n```\n:::\n:::\n\n\n:::\n\n### Two-Dimensional Datasets\nTwo-dimensional datasets organize values in a **matrix** or a **data frame** consisting of rows and columns. A matrix contains only one data type (e.g., numbers), while a data frame can contain different data types (e.g., numbers and boolean values). In Python, the Pandas module provides the DataFrame structure (see [Pandas Fundamentals module](https://bausteine-der-datenanalyse.github.io/w-pandas/output/book/)).\n\n::: {.border}\n![two-dimensional dataset](00-bilder/zweidimensionaler-datensatz-slicing-mf-mp.png){width=\"45%\" fig-alt=\"A two-dimensional block represents a two-dimensional dataset. Arrows indicate the two axes. Axis 0 corresponds to the dataset’s length (top to bottom), and axis 1 corresponds to its width.\"}\n\n*slicing* by Marc Fehr is licensed under [CC-BY-4.0](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file) and available on [GitHub](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen). The graphic was cropped to show only the relevant part and the top label removed. 2024\n:::\n\n&nbsp;\n\nTypically, in two-dimensional datasets, each column represents a **variable** and each row represents an **observation**. Variables store all values of a feature, for example, dice results. Observations store all measured values for one observation unit, e.g., a person. [@Wickham-2014, p. 3]\n\n::: {#e3e3fa1c .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\nmeasurement1 = pd.DataFrame({\n    'Name': ['Hans', 'Elke', 'Jean', 'Maya'],\n    'Birthday': ['26.02.', '14.03.', '30.12.', '07.09.'],\n    'Dice Color': ['pink', 'pink', 'blue', 'yellow'],\n    'Sum of Eyes': [17, 12, 8, 23]\n})\n\nmeasurement1\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Birthday</th>\n      <th>Dice Color</th>\n      <th>Sum of Eyes</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>pink</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>pink</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>blue</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>yellow</td>\n      <td>23</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n&nbsp;\n\nBy specifying the indices along axis 0 (rows) and axis 1 (columns), you can output the sum of dice eyes for a person.\n\n::: {#74fa3bc8 .cell execution_count=5}\n``` {.python .cell-code}\nprint(f\"Jean rolled {measurement1.iloc[2, 3]} eyes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nJean rolled 8 eyes\n```\n:::\n:::\n\n\nIt is also possible to first select a column and then access the value at a specific index, as with a one-dimensional dataset. This is called **chained indexing**.\n\n::: {#fef9fd9f .cell execution_count=6}\n``` {.python .cell-code}\nprint(f\"Jean rolled {measurement1['Sum of Eyes'][2]} eyes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nJean rolled 8 eyes\n```\n:::\n:::\n\n\n::: {#wrn-chainedassignment .callout-warning appearance=\"simple\"}\n## Chained Indexing\n\nChained indexing in Pandas may either create a copy of the object or access the object’s memory directly, depending on the context. With Pandas 3.0, chained indexing will no longer be supported, and creating a copy will become the default. More information can be found at the linked reference.\n\n:::: {.border layout=\"[5, 90, 5]\"}\n\n&nbsp;\n\n\"Whether a copy or a reference is returned for a setting operation may depend on the context. This is sometimes called `chained assignment` and should be avoided. See [Returning a View versus Copy](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-view-versus-copy).\"\n\n&nbsp;\n\n::::\n\n([Pandas Documentation](https://pandas.pydata.org/docs/user_guide/indexing.html))\n:::\n\n### Long and Wide Format\nTwo-dimensional datasets are usually represented as a matrix of rows and columns. Values for the variables organized in columns are assigned to the observations entered row-wise. This way of representing data is called the **wide format**: each additional measured variable makes the dataset wider.\n\nAnother way to organize and think about data is the **long format**. Some programs and packages require or at least benefit from data in long format, for example when creating plots. Let’s first look at the dataset `measurement1` again in wide format. What are the observation units? Which variables were recorded?\n\n::: {#59376c4b .cell execution_count=7}\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Birthday</th>\n      <th>Dice Color</th>\n      <th>Sum of Eyes</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>pink</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>pink</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>blue</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>yellow</td>\n      <td>23</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n&nbsp;\n\nYou might assume that the observation units are Hans, Elke, Jean, and Maya, and that the variables are Birthday, Dice Color, and Sum of Eyes. However, it is also possible that the observation unit is Person, encoded as 0, 1, 2, and 3 (the row index of the dataset), and that the column Name is one of the recorded variables. Similarly, there could be only two variables, Dice Color and Sum of Eyes, while the columns Name and Birthday encode the observed individuals. Imagine there is a second person named Hans. In that case, the dice results for individuals named Hans can only be correctly assigned using the Birthday, e.g., 26.02. or 11.11.\n\n::: {#28b47bb4 .cell execution_count=8}\n``` {.python .cell-code}\nmeasurement1 = pd.DataFrame({\n    'Name': ['Hans', 'Elke', 'Jean', 'Maya', 'Hans'],\n    'Birthday': ['26.02.', '14.03.', '30.12.', '07.09.', '11.11.'],\n    'Dice Color': ['pink', 'pink', 'blue', 'yellow', 'pink'],\n    'Sum of Eyes': [12, 17, 8, 23, 7]\n})\n\nmeasurement1\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Birthday</th>\n      <th>Dice Color</th>\n      <th>Sum of Eyes</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>pink</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>pink</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>blue</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>yellow</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Hans</td>\n      <td>11.11.</td>\n      <td>pink</td>\n      <td>7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n&nbsp;\n\nThe long format makes these considerations explicit by distinguishing between **identification variables** (id variables) and **measured variables** (measure variables or value vars). Transforming a dataset from wide format to long format is called **melting**. The Pandas module provides the function `pd.melt(frame, id_vars=None)`. It expects a DataFrame, and the optional argument `id_vars` specifies which columns are the identification variables.\n\n::: {#bd90c64f .cell execution_count=9}\n``` {.python .cell-code}\nmeasurement1_long = pd.melt(measurement1, id_vars = ['Name', 'Birthday'])\n\nmeasurement1_long\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Birthday</th>\n      <th>variable</th>\n      <th>value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>Dice Color</td>\n      <td>blue</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>Dice Color</td>\n      <td>yellow</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Hans</td>\n      <td>11.11.</td>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>Sum of Eyes</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>Sum of Eyes</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>Sum of Eyes</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>Sum of Eyes</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Hans</td>\n      <td>11.11.</td>\n      <td>Sum of Eyes</td>\n      <td>7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n&nbsp;\n\nIn long format, the measured variables are listed in the column `variable`, and their values are stored in the column `value`. Each additional measured variable makes the dataset longer.\n\nIf you think through the distinction between identification and measured variables, the variable name itself can be considered an identification variable for the value in the `value` column. A dataset can be understood as a structure that has exactly one measured variable, `value`, and a number of identification variables. This can be represented in long format as follows:\n\n::: {#0fb328b9 .cell execution_count=10}\n``` {.python .cell-code}\nmeasurement1_all_id = pd.melt(measurement1, id_vars = ['Name', 'Birthday', 'Dice Color'])\n\nmeasurement1_all_id\n```\n:::\n\n\nIn this representation, for example, the first value `12` is identified by `Name = Hans`, `Birthday = 26.02.`, `Dice Color = pink`, and `variable = Sum of Eyes`.\n\n::: {layout=\"[70, 30]\"}\n\n::: {#65c6b465 .cell execution_count=11}\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Birthday</th>\n      <th>Dice Color</th>\n      <th>variable</th>\n      <th>value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>pink</td>\n      <td>Sum of Eyes</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>pink</td>\n      <td>Sum of Eyes</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>blue</td>\n      <td>Sum of Eyes</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>yellow</td>\n      <td>Sum of Eyes</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Hans</td>\n      <td>11.11.</td>\n      <td>pink</td>\n      <td>Sum of Eyes</td>\n      <td>7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n![](00-bilder/5f489ffabc91dec1ec2192dc4e993e00.jpg){width=\"90%\" fig-alt=\"Decorative image of a surprised dog\"} \n\n<!-- wow will be removed again ;-) -->\n\n::: \n\n::: {.border}\nMuch wow. Such architecture. by Dmitry Kudryavtsev is available at <https://yieldcode.blog/post/bloat-in-software-engineering/>. **The image will likely be removed again.**\n:::\n\n**What happens if the variable `Sum of Eyes` is also passed to the `id_vars` argument?**\n\n::: {#tip-Antwort-all-id .callout-tip collapse=\"true\"}\n## Answer\n\nThe command `measurement1_all_id = pd.melt(measurement1, id_vars = ['Name', 'Birthday', 'Dice Color', 'Sum of Eyes'])` produces an empty DataFrame because no measured values remain.\n:::\n\nThe reverse case is also possible: if no `id_vars` are specified during melting, all columns are treated as measured variables.\n\n::: {#f432a447 .cell execution_count=12}\n``` {.python .cell-code}\nmeasurement1_no_id = pd.melt(measurement1)\n\nmeasurement1_no_id\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>variable</th>\n      <th>value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Name</td>\n      <td>Hans</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Name</td>\n      <td>Elke</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Name</td>\n      <td>Jean</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Name</td>\n      <td>Maya</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Name</td>\n      <td>Hans</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Birthday</td>\n      <td>26.02.</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Birthday</td>\n      <td>14.03.</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Birthday</td>\n      <td>30.12.</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Birthday</td>\n      <td>07.09.</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Birthday</td>\n      <td>11.11.</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Dice Color</td>\n      <td>blue</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Dice Color</td>\n      <td>yellow</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Sum of Eyes</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Sum of Eyes</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>Sum of Eyes</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Sum of Eyes</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Sum of Eyes</td>\n      <td>7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n&nbsp;\n\nThe reverse operation of melting is called **casting** or **pivoting**. Here, a dataset in long format is converted back to wide format. The Pandas function `pd.pivot(data, columns, index)` takes a melted DataFrame and converts it using the unique values in `columns` (the column names of the wide-format DataFrame) and the unique values in `index` (the row index of the wide-format DataFrame). If no column is provided for `index`, the existing index of the melted DataFrame is used (which, with 20 rows, is of course too long). Since the object `measurement1_no_id` does not have a suitable index column, one must be created before casting. This can be done with the method `measurement1_no_id.groupby('variable').cumcount()`, which counts the occurrence of each value in the specified column starting at 0. (Directly replacing the index is not possible in this way, because the index passed to `pd.pivot(data, columns, index)` must not contain duplicates.)\n\n::: {#2214fff9 .cell execution_count=13}\n``` {.python .cell-code}\n# pd.pivot() requires an index or uses the existing index of the melted_df, which is too long\n# Therefore, insert an additional column in measurement1_no_id\n## simple: measurement1_no_id['new_index'] = list(range(0, 5)) * 4 \n## general: measurement1_no_id['new_index'] = measurement1_no_id.groupby('variable').cumcount()\n\n# Insert new_index column\nmeasurement1_no_id['new_index'] = measurement1_no_id.groupby('variable').cumcount()\nprint(f\"The long-format dataset with additional column new_index:\\n{measurement1_no_id}\")\n\n# casting\nmeasurement1_cast = pd.pivot(measurement1_no_id, index='new_index', columns='variable', values='value')\nprint(f\"\\nThe dataset in wide format:\\n{measurement1_cast}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe long-format dataset with additional column new_index:\n       variable   value  new_index\n0          Name    Hans          0\n1          Name    Elke          1\n2          Name    Jean          2\n3          Name    Maya          3\n4          Name    Hans          4\n5      Birthday  26.02.          0\n6      Birthday  14.03.          1\n7      Birthday  30.12.          2\n8      Birthday  07.09.          3\n9      Birthday  11.11.          4\n10   Dice Color    pink          0\n11   Dice Color    pink          1\n12   Dice Color    blue          2\n13   Dice Color  yellow          3\n14   Dice Color    pink          4\n15  Sum of Eyes      12          0\n16  Sum of Eyes      17          1\n17  Sum of Eyes       8          2\n18  Sum of Eyes      23          3\n19  Sum of Eyes       7          4\n\nThe dataset in wide format:\nvariable  Birthday Dice Color  Name Sum of Eyes\nnew_index                                      \n0           26.02.       pink  Hans          12\n1           14.03.       pink  Elke          17\n2           30.12.       blue  Jean           8\n3           07.09.     yellow  Maya          23\n4           11.11.       pink  Hans           7\n```\n:::\n:::\n\n\nThe result still does not match the original wide-format dataset. To restore the original format, the columns must be reordered, and the index and its label must be reset.\n\n::: {#2a303802 .cell execution_count=14}\n``` {.python .cell-code}\n# Reorder columns and reset index\nmeasurement1_cast = measurement1_cast[['Name', 'Birthday', 'Dice Color', 'Sum of Eyes']]\nmeasurement1_cast.reset_index(drop=True, inplace=True)\nmeasurement1_cast.rename_axis(None, axis=1, inplace=True)\n\nprint(f\"\\nThe dataset in wide format with reset index:\\n\\n{measurement1_cast}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nThe dataset in wide format with reset index:\n\n   Name Birthday Dice Color Sum of Eyes\n0  Hans   26.02.       pink          12\n1  Elke   14.03.       pink          17\n2  Jean   30.12.       blue           8\n3  Maya   07.09.     yellow          23\n4  Hans   11.11.       pink           7\n```\n:::\n:::\n\n\n::: {#tip-idvars .callout-tip collapse=\"false\"}\n## Identification and Measured Variables\n\nEven when working with wide-format datasets, distinguishing between identification and measured variables is useful for organizing data. [see @sec-tidydata]\n\n:::\n\n### Exercise: Two-Dimensional Datasets\nAbove, the object `measurement1_long` was created using the command `measurement1_long = pd.melt(measurement1, id_vars = ['Name', 'Birthday'])`.  \n**Use the function** `pd.DataFrame.pivot()` **to transform the dataset `measurement1` back into wide format.**\n\n::: {#4250b989 .cell execution_count=15}\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Birthday</th>\n      <th>variable</th>\n      <th>value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>Dice Color</td>\n      <td>blue</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>Dice Color</td>\n      <td>yellow</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Hans</td>\n      <td>11.11.</td>\n      <td>Dice Color</td>\n      <td>pink</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>Sum of Eyes</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>Sum of Eyes</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>Sum of Eyes</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>Sum of Eyes</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Hans</td>\n      <td>11.11.</td>\n      <td>Sum of Eyes</td>\n      <td>7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tip-pivoting .callout-tip collapse=\"true\"}\n## Example Solution: Two-Dimensional Datasets\n\n::: {#9b809f33 .cell execution_count=16}\n``` {.python .cell-code}\n# Insert new_index column\nmeasurement1_long['new_index'] = measurement1_long.groupby('variable').cumcount()\n\n# casting\nmeasurement1_long_cast = pd.pivot(measurement1_long, index='new_index', columns='variable', values='value')\n\n# Reorder columns and reset index\nmeasurement1_long_cast = measurement1_cast[['Name', 'Birthday', 'Dice Color', 'Sum of Eyes']]\nmeasurement1_long_cast.reset_index(drop=True, inplace=True)\nmeasurement1_long_cast.rename_axis(None, axis=1, inplace=True)\n\nmeasurement1_long_cast\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Birthday</th>\n      <th>Dice Color</th>\n      <th>Sum of Eyes</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hans</td>\n      <td>26.02.</td>\n      <td>pink</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Elke</td>\n      <td>14.03.</td>\n      <td>pink</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Jean</td>\n      <td>30.12.</td>\n      <td>blue</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Maya</td>\n      <td>07.09.</td>\n      <td>yellow</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Hans</td>\n      <td>11.11.</td>\n      <td>pink</td>\n      <td>7</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n\n### Three- and Higher-Dimensional Datasets\nThree- or higher-dimensional datasets organize complex data structures in **arrays**. Arrays are n-dimensional data structures and therefore a general concept. For example, a list is a one-dimensional array, a matrix is a two-dimensional array, and an Excel file with multiple sheets for annually collected survey data is a three-dimensional array (sheets, rows, columns). Depending on the module used, arrays may contain one or multiple data types.\n\n<!-- optionally add: xarray module <https://docs.xarray.dev/en/stable/user-guide/pandas.html> -->\n\n::: {.border}\n![three-dimensional datasets](00-bilder/dreidimensionaler-datensatz-slicing-mf-mp.png){width=\"50%\" fig-alt=\"A three-dimensional block representing a three-dimensional dataset. Arrows indicate the three axes. Axis 0 corresponds to depth, axis 1 to length (top to bottom), and axis 2 to width of the dataset.\"}\n\n*slicing* by Marc Fehr is licensed under [CC-BY-4.0](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file) and available on [GitHub](https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen). The graphic was cropped to show only the relevant part and the top label removed. 2024\n\n:::\n\n&nbsp;\n\nFor three- and higher-dimensional data structures, specialized data formats are often used, as discussed in section @sec-specialformats. This is partly because it makes it easier to process different data types and document them with metadata (see @sec-metadata).\n\n**Optional: Excursus JSON <https://docs.python.org/3/tutorial/inputoutput.html>**\n\n#### Reading Image Data\n\n::: {.border}\nDigital images are represented as three-dimensional datasets. Each pixel in the rows and columns has color values (Red, Green, Blue) and optionally an alpha channel (Red, Green, Blue, Alpha). The color values are either in the range 0–1 or 0–255 (8-bit).\n\n```\n# Color values for one pixel\n[Red, Green, Blue]\n\n# One image row with three pixels\n[[Red, Green, Blue], [Red, Green, Blue], [Red, Green, Blue]]\n\n# An image with three rows and three columns\n[[[Red, Green, Blue], [Red, Green, Blue], [Red, Green, Blue]],\n [[Red, Green, Blue], [Red, Green, Blue], [Red, Green, Blue]],\n [[Red, Green, Blue], [Red, Green, Blue], [Red, Green, Blue]]]\n```\n\nImage files can be read using the function `plt.imread()` from the `matplotlib.pyplot` module.\n\n:::: {.border}\n\n::: {#7ff0a84a .cell execution_count=17}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nlogo = plt.imread(fname='00-bilder/python-logo-and-wordmark-cc0-tm.png')\n\nplt.imshow(logo)\n```\n\n::: {.cell-output .cell-output-display}\n![](grundlagen_files/figure-html/cell-18-output-1.png){width=575 height=200}\n:::\n:::\n\n\nThe Python logo by the Python Software Foundation is licensed under the [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html). The wordmark is trademarked: <https://www.python.org/psf/trademarks/>. The file is available on [Wikimedia](https://de.m.wikipedia.org/wiki/Datei:Python_logo_and_wordmark.svg). 2008\n\n:::: \n\n&nbsp;\n\nThe structure of the dataset can be accessed using the `.shape` attribute.\n\n::: {#0748d087 .cell execution_count=18}\n``` {.python .cell-code}\nprint(type(logo), \"\\n\")\n\nprint(logo.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'numpy.ndarray'> \n\n(144, 486, 4)\n```\n:::\n:::\n\n\nThe data was read as a `NumPy.ndarray`. The logo has 144 rows, 486 columns, and is in the RGBA color space. A slice of the data looks like this:\n\n::: {#630e1f64 .cell execution_count=19}\n``` {.python .cell-code}\nprint(logo[50:52, 50:52, :])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[[0.21568628 0.44705883 0.63529414 1.        ]\n  [0.21568628 0.44705883 0.63529414 1.        ]]\n\n [[0.21568628 0.44705883 0.63529414 1.        ]\n  [0.21176471 0.44313726 0.6313726  1.        ]]]\n```\n:::\n:::\n\n\n[@Arnold-2023-numpy-dateien]\n\n:::\n\n### Exercise: Three-Dimensional Datasets\nUsing the index of the third dimension, the Red, Green, and Blue color channels can be selected and displayed individually with the function `plt.imshow(cmap='Greys_r')`. The argument `cmap='Greys_r'` instructs the function to use the inverted grayscale, so high color values appear light and low values dark. **Display the Red, Green, and Blue channels of the Python logo individually using `plt.imshow(cmap='Greys_r')`.**\n\n::: {#tip-logo .callout-tip collapse=\"true\"}\n## Example Solution: Three-Dimensional Datasets\n\n::: {#a7a9d144 .cell execution_count=20}\n``` {.python .cell-code}\nchannels = [\"Red Channel\", \"Green Channel\", \"Blue Channel\"]\n\nplt.figure(figsize=(9, 6))\n\nfor i in range(3):\n    plt.subplot(1, 4, i + 1)\n    plt.imshow(logo[:, :, i], cmap='Greys_r')\n    plt.title(label=channels[i])\n\nplt.colorbar(shrink=0.15)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Color channels of the Python logo](grundlagen_files/figure-html/cell-21-output-1.png){width=652 height=114 fig-alt='The three color channels of the Python logo are shown.'}\n:::\n:::\n\n\nYou might wonder why the image background appears black in each color channel. The explanation is in the next tip.\n\n:::: {#tip-logo .callout-tip collapse=\"true\"}\n## Explanation: Image Background\nThe image background has a value of 0 in all channels, including the alpha channel. This part of the image is therefore fully transparent and is filled in by the webpage background. As a result, the logo's background appears white.\n\n::: {#9f480d20 .cell execution_count=21}\n``` {.python .cell-code}\n# Alpha channel\nplt.imshow(logo[:, :, 3], cmap='Greys_r')\nplt.title(label='Alpha Channel')\nplt.colorbar(shrink=0.4)\n\nplt.show()\n\n# The first two rows and columns of the logo\nprint(logo[0:2, 0:2, :])\n```\n\n::: {.cell-output .cell-output-display}\n![Alpha channel of the Python logo](grundlagen_files/figure-html/cell-22-output-1.png){width=534 height=185 fig-alt='The alpha channel of the Python logo is shown. The image background has a value of 0.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[[[0. 0. 0. 0.]\n  [0. 0. 0. 0.]]\n\n [[0. 0. 0. 0.]\n  [0. 0. 0. 0.]]]\n```\n:::\n:::\n\n\n::::\n:::\n\n## Data Type {#sec-datentyp}\nThe data type specifies how the values contained in a dataset are interpreted by Python. For example, the value \"1\" could represent a character, an integer, a Boolean value, the month January, or the level of a categorical variable. Python, as a versatile programming language, supports many data types that fall into the categories: numerics, sequences, mappings, classes, instances, and exceptions. More information can be found in the [documentation](https://docs.python.org/3/library/stdtypes.html).\n\n::: {.border}\n![Data types in Python](00-bilder/python3-standard-type-hierarchy.png){width=\"60%\" fig-alt=\"A categorization of standard types in Python. The categorization does not exactly match the categories listed in the documentation. The type None for null values has no further subdivision. The Numbers category is divided into integers (including Booleans), real numbers (floats), and complex numbers. The Sequences category is divided into immutable (Strings, Tuples, Bytes) and mutable (Lists, Byte Arrays). The Set Types category is divided into Sets and Frozen Sets. The Mappings category contains Dictionaries. The Callable category includes functions, methods, and classes. There is also the Module category.\"}\n\nPython 3. The standard type hierarchy. by Максим Пе is licensed under [CC BY SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.de) and available on [Wikimedia](https://commons.wikimedia.org/wiki/File:Python_3._The_standard_type_hierarchy.png). 2018\n:::\n\n&nbsp;\n\nModules add further data types. Commonly used data types in data analysis include:\n\n  - Numbers: integers, floating-point numbers\n  - Booleans\n  - Strings\n  - Date and time values\n  - Category (from the [Pandas](https://pandas.pydata.org/docs/user_guide/categorical.html) module)\n\nThe data type determines, on the one hand, the allowable range of values for a variable. For example, 0 and 13 are valid integers but not valid encodings for a month. On the other hand, the data type defines which operations are allowed on the values and how Python executes them. This applies to operators and functions. Python includes functions to determine and, if necessary, convert the data type of a value (see w-Python).\n\n::: {#nte-operation-nach-datentyp .callout-note}\n\n",
    "supporting": [
      "grundlagen_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}